// Phases for workflow: Companies
      
import { Companies_FieldIds, Companies_PhaseIds } from "../enums";
      
export const phases: HailerPhaseUpdatePayload[] = [
  {
    _id: Companies_PhaseIds.leads_a5b,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    fields: [
      Companies_FieldIds.accounting_a52,
      Companies_FieldIds.signing_probability_a54,
      Companies_FieldIds.financial_statement_c35,
      Companies_FieldIds.total_mrr_d67,
      Companies_FieldIds.payroll_de0,
      Companies_FieldIds.licenses_accounting_f80,
      Companies_FieldIds.other_services_8f4,
      Companies_FieldIds.time_spent_total_cea,
      Companies_FieldIds.ohjausryhm_43a,
      Companies_FieldIds.admin_45f,
      Companies_FieldIds.category_2b4,
      Companies_FieldIds.sold_accounting_services_643,
      Companies_FieldIds.accounting_for_bank_statements_reference_payments_6e6,
      Companies_FieldIds.recording_of_purchase_invoices_7ac,
      Companies_FieldIds.depreciation_7dc,
      Companies_FieldIds.closing_of_the_settlement_account_80c,
      Companies_FieldIds.recording_of_inventory_values_83c,
      Companies_FieldIds.recording_of_sales_from_another_system_886,
      Companies_FieldIds.deferred_taxes_8b7,
      Companies_FieldIds.checking_the_accounts_receivable_ledger_8f8,
      Companies_FieldIds.sold_payroll_services_927,
      Companies_FieldIds.hourly_entries_9df,
      Companies_FieldIds.payroll_accounting_a10,
      Companies_FieldIds.salaries_sent_for_approval_a45,
      Companies_FieldIds.salaries_paid_a97,
      Companies_FieldIds.holiday_pay_reserve_vacation_days_aea,
      Companies_FieldIds.obligations_netvisor_term_b76,
      Companies_FieldIds.separate_report_bbd,
      Companies_FieldIds.separate_report_payment_c04,
      Companies_FieldIds.travel_expenses_c65,
      Companies_FieldIds.contents_of_the_financial_statements_c9e,
      Companies_FieldIds.old_fields_ce4,
      Companies_FieldIds.adjustments_to_depreciation_d59,
      Companies_FieldIds.tax_accrual_d70,
      Companies_FieldIds.all_balance_sheet_accounts_checked_df4,
      Companies_FieldIds.advance_tax_e2c,
      Companies_FieldIds.financial_statement_ready_e7f,
      Companies_FieldIds.financial_statement_signed_eaf,
      Companies_FieldIds.audited_ee3,
      Companies_FieldIds.tax_return_filed_f2c,
      Companies_FieldIds.annual_general_meeting_f5b,
      Companies_FieldIds.financial_statement_registered_f90,
      Companies_FieldIds.dividend_report_fc6,
      Companies_FieldIds.dividend_tax_paid_ff5,
      Companies_FieldIds.annual_dividend_report_024,
      Companies_FieldIds.dividend_recorded_05e,
      Companies_FieldIds.accounting_deadline_434,
      Companies_FieldIds.payroll_deadline_463,
      Companies_FieldIds.person_responsible_for_financial_statements_66c,
      Companies_FieldIds.ytunnus_b80,
      Companies_FieldIds.company_info_762,
      Companies_FieldIds.fiscal_year_03b,
      Companies_FieldIds.deadline_for_financial_statement_16d,
      Companies_FieldIds.person_responsible_for_accounting_ba4,
      Companies_FieldIds.person_responsible_for_payroll_c04,
      Companies_FieldIds.person_responsible_for_client_6ba,
      Companies_FieldIds.shares_cd1,
      Companies_FieldIds.shares_listing_d5f,
      Companies_FieldIds.shares_metadata_f65,
      Companies_FieldIds.fiscal_year_updated_in_hailer_cdb,
      Companies_FieldIds.vat_calculation_created_618,
      Companies_FieldIds.vat_report_sent_61b,
      Companies_FieldIds.vat_paid_61f
    ],
    followers: [],
    isInitial: true,
    name: "🥚 Leads",
    possibleNextPhase: [
      Companies_PhaseIds.active_contact_a5c,
      Companies_PhaseIds.churn_a5e,
      Companies_PhaseIds.customers_a60
    ],
    possibleNextPhaseSettings: {
      [Companies_PhaseIds.active_contact_a5c]: {
        text: "Moved to Forecast"
      },
      "677393544e9c3c0478e35a5d": {
        text: "Order Received"
      },
      [Companies_PhaseIds.churn_a5e]: {
        text: "Project Lost"
      }
    }
  },
  {
    _id: Companies_PhaseIds.active_contact_a5c,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    fields: [
      Companies_FieldIds.accounting_a52,
      Companies_FieldIds.signing_probability_a54,
      Companies_FieldIds.est_signing_date_a55,
      Companies_FieldIds.financial_statement_c35,
      Companies_FieldIds.total_mrr_d67,
      Companies_FieldIds.payroll_de0,
      Companies_FieldIds.licenses_accounting_f80,
      Companies_FieldIds.other_services_8f4,
      Companies_FieldIds.time_spent_total_cea,
      Companies_FieldIds.ohjausryhm_43a,
      Companies_FieldIds.admin_45f,
      Companies_FieldIds.category_2b4,
      Companies_FieldIds.sold_accounting_services_643,
      Companies_FieldIds.accounting_for_bank_statements_reference_payments_6e6,
      Companies_FieldIds.recording_of_purchase_invoices_7ac,
      Companies_FieldIds.depreciation_7dc,
      Companies_FieldIds.closing_of_the_settlement_account_80c,
      Companies_FieldIds.recording_of_inventory_values_83c,
      Companies_FieldIds.recording_of_sales_from_another_system_886,
      Companies_FieldIds.deferred_taxes_8b7,
      Companies_FieldIds.checking_the_accounts_receivable_ledger_8f8,
      Companies_FieldIds.sold_payroll_services_927,
      Companies_FieldIds.hourly_entries_9df,
      Companies_FieldIds.payroll_accounting_a10,
      Companies_FieldIds.salaries_sent_for_approval_a45,
      Companies_FieldIds.salaries_paid_a97,
      Companies_FieldIds.holiday_pay_reserve_vacation_days_aea,
      Companies_FieldIds.obligations_netvisor_term_b76,
      Companies_FieldIds.separate_report_bbd,
      Companies_FieldIds.separate_report_payment_c04,
      Companies_FieldIds.travel_expenses_c65,
      Companies_FieldIds.contents_of_the_financial_statements_c9e,
      Companies_FieldIds.old_fields_ce4,
      Companies_FieldIds.adjustments_to_depreciation_d59,
      Companies_FieldIds.tax_accrual_d70,
      Companies_FieldIds.all_balance_sheet_accounts_checked_df4,
      Companies_FieldIds.advance_tax_e2c,
      Companies_FieldIds.financial_statement_ready_e7f,
      Companies_FieldIds.financial_statement_signed_eaf,
      Companies_FieldIds.audited_ee3,
      Companies_FieldIds.tax_return_filed_f2c,
      Companies_FieldIds.annual_general_meeting_f5b,
      Companies_FieldIds.financial_statement_registered_f90,
      Companies_FieldIds.dividend_report_fc6,
      Companies_FieldIds.dividend_tax_paid_ff5,
      Companies_FieldIds.annual_dividend_report_024,
      Companies_FieldIds.dividend_recorded_05e,
      Companies_FieldIds.accounting_deadline_434,
      Companies_FieldIds.payroll_deadline_463,
      Companies_FieldIds.person_responsible_for_financial_statements_66c,
      Companies_FieldIds.ytunnus_b80,
      Companies_FieldIds.company_info_762,
      Companies_FieldIds.fiscal_year_03b,
      Companies_FieldIds.deadline_for_financial_statement_16d,
      Companies_FieldIds.person_responsible_for_accounting_ba4,
      Companies_FieldIds.person_responsible_for_payroll_c04,
      Companies_FieldIds.person_responsible_for_client_6ba,
      Companies_FieldIds.shares_cd1,
      Companies_FieldIds.shares_listing_d5f,
      Companies_FieldIds.shares_metadata_f65,
      Companies_FieldIds.fiscal_year_updated_in_hailer_cdb,
      Companies_FieldIds.vat_calculation_created_618,
      Companies_FieldIds.vat_report_sent_61b,
      Companies_FieldIds.vat_paid_61f
    ],
    followers: [],
    isInitial: false,
    name: "🐣 Active contact",
    possibleNextPhase: [
      Companies_PhaseIds.churn_a5e,
      Companies_PhaseIds.customers_a60,
      Companies_PhaseIds.leads_a5b
    ],
    possibleNextPhaseSettings: {
      "677393544e9c3c0478e35a5d": {
        text: "Order Received"
      },
      [Companies_PhaseIds.churn_a5e]: {
        text: "Project Lost"
      }
    },
    primaryDateField: Companies_FieldIds.est_signing_date_a55,
    primaryNumericField: Companies_FieldIds.total_mrr_d67
  },
  {
    _id: Companies_PhaseIds.customers_a60,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    fields: [
      Companies_FieldIds.accounting_a52,
      Companies_FieldIds.customer_satisfaction_a59,
      Companies_FieldIds.financial_statement_c35,
      Companies_FieldIds.total_mrr_d67,
      Companies_FieldIds.payroll_de0,
      Companies_FieldIds.licenses_accounting_f80,
      Companies_FieldIds.other_services_8f4,
      Companies_FieldIds.time_spent_total_cea,
      Companies_FieldIds.ohjausryhm_43a,
      Companies_FieldIds.admin_45f,
      Companies_FieldIds.category_2b4,
      Companies_FieldIds.sold_accounting_services_643,
      Companies_FieldIds.accounting_for_bank_statements_reference_payments_6e6,
      Companies_FieldIds.recording_of_purchase_invoices_7ac,
      Companies_FieldIds.depreciation_7dc,
      Companies_FieldIds.closing_of_the_settlement_account_80c,
      Companies_FieldIds.recording_of_inventory_values_83c,
      Companies_FieldIds.recording_of_sales_from_another_system_886,
      Companies_FieldIds.deferred_taxes_8b7,
      Companies_FieldIds.checking_the_accounts_receivable_ledger_8f8,
      Companies_FieldIds.sold_payroll_services_927,
      Companies_FieldIds.hourly_entries_9df,
      Companies_FieldIds.payroll_accounting_a10,
      Companies_FieldIds.salaries_sent_for_approval_a45,
      Companies_FieldIds.salaries_paid_a97,
      Companies_FieldIds.holiday_pay_reserve_vacation_days_aea,
      Companies_FieldIds.obligations_netvisor_term_b76,
      Companies_FieldIds.separate_report_bbd,
      Companies_FieldIds.separate_report_payment_c04,
      Companies_FieldIds.travel_expenses_c65,
      Companies_FieldIds.contents_of_the_financial_statements_c9e,
      Companies_FieldIds.old_fields_ce4,
      Companies_FieldIds.adjustments_to_depreciation_d59,
      Companies_FieldIds.tax_accrual_d70,
      Companies_FieldIds.all_balance_sheet_accounts_checked_df4,
      Companies_FieldIds.advance_tax_e2c,
      Companies_FieldIds.financial_statement_ready_e7f,
      Companies_FieldIds.financial_statement_signed_eaf,
      Companies_FieldIds.audited_ee3,
      Companies_FieldIds.tax_return_filed_f2c,
      Companies_FieldIds.annual_general_meeting_f5b,
      Companies_FieldIds.financial_statement_registered_f90,
      Companies_FieldIds.dividend_report_fc6,
      Companies_FieldIds.dividend_tax_paid_ff5,
      Companies_FieldIds.annual_dividend_report_024,
      Companies_FieldIds.dividend_recorded_05e,
      Companies_FieldIds.accounting_deadline_434,
      Companies_FieldIds.payroll_deadline_463,
      Companies_FieldIds.person_responsible_for_financial_statements_66c,
      Companies_FieldIds.ytunnus_b80,
      Companies_FieldIds.company_info_762,
      Companies_FieldIds.fiscal_year_03b,
      Companies_FieldIds.deadline_for_financial_statement_16d,
      Companies_FieldIds.person_responsible_for_accounting_ba4,
      Companies_FieldIds.person_responsible_for_payroll_c04,
      Companies_FieldIds.person_responsible_for_client_6ba,
      Companies_FieldIds.shares_cd1,
      Companies_FieldIds.shares_listing_d5f,
      Companies_FieldIds.shares_metadata_f65,
      Companies_FieldIds.systems_9df,
      Companies_FieldIds.systems_in_use_a25,
      Companies_FieldIds.fiscal_year_updated_in_hailer_cdb,
      Companies_FieldIds.vat_calculation_created_618,
      Companies_FieldIds.vat_report_sent_61b,
      Companies_FieldIds.vat_paid_61f
    ],
    followers: [],
    isInitial: false,
    name: "🐤 Customers",
    possibleNextPhase: [
      Companies_PhaseIds.leads_a5b,
      Companies_PhaseIds.active_contact_a5c,
      Companies_PhaseIds.churn_a5e
    ],
    possibleNextPhaseSettings: {},
    primaryNumericField: Companies_FieldIds.total_mrr_d67
  },
  {
    _id: Companies_PhaseIds.churn_a5e,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    fields: [
      Companies_FieldIds.accounting_a52,
      Companies_FieldIds.lost_for_reason_a58,
      Companies_FieldIds.financial_statement_c35,
      Companies_FieldIds.total_mrr_d67,
      Companies_FieldIds.payroll_de0,
      Companies_FieldIds.licenses_accounting_f80,
      Companies_FieldIds.other_services_8f4,
      Companies_FieldIds.time_spent_total_cea,
      Companies_FieldIds.ohjausryhm_43a,
      Companies_FieldIds.admin_45f,
      Companies_FieldIds.category_2b4,
      Companies_FieldIds.sold_accounting_services_643,
      Companies_FieldIds.accounting_for_bank_statements_reference_payments_6e6,
      Companies_FieldIds.recording_of_purchase_invoices_7ac,
      Companies_FieldIds.depreciation_7dc,
      Companies_FieldIds.closing_of_the_settlement_account_80c,
      Companies_FieldIds.recording_of_inventory_values_83c,
      Companies_FieldIds.recording_of_sales_from_another_system_886,
      Companies_FieldIds.deferred_taxes_8b7,
      Companies_FieldIds.checking_the_accounts_receivable_ledger_8f8,
      Companies_FieldIds.sold_payroll_services_927,
      Companies_FieldIds.hourly_entries_9df,
      Companies_FieldIds.payroll_accounting_a10,
      Companies_FieldIds.salaries_sent_for_approval_a45,
      Companies_FieldIds.salaries_paid_a97,
      Companies_FieldIds.holiday_pay_reserve_vacation_days_aea,
      Companies_FieldIds.obligations_netvisor_term_b76,
      Companies_FieldIds.separate_report_bbd,
      Companies_FieldIds.separate_report_payment_c04,
      Companies_FieldIds.travel_expenses_c65,
      Companies_FieldIds.contents_of_the_financial_statements_c9e,
      Companies_FieldIds.old_fields_ce4,
      Companies_FieldIds.adjustments_to_depreciation_d59,
      Companies_FieldIds.tax_accrual_d70,
      Companies_FieldIds.all_balance_sheet_accounts_checked_df4,
      Companies_FieldIds.advance_tax_e2c,
      Companies_FieldIds.financial_statement_ready_e7f,
      Companies_FieldIds.financial_statement_signed_eaf,
      Companies_FieldIds.audited_ee3,
      Companies_FieldIds.tax_return_filed_f2c,
      Companies_FieldIds.annual_general_meeting_f5b,
      Companies_FieldIds.financial_statement_registered_f90,
      Companies_FieldIds.dividend_report_fc6,
      Companies_FieldIds.dividend_tax_paid_ff5,
      Companies_FieldIds.annual_dividend_report_024,
      Companies_FieldIds.dividend_recorded_05e,
      Companies_FieldIds.accounting_deadline_434,
      Companies_FieldIds.payroll_deadline_463,
      Companies_FieldIds.person_responsible_for_financial_statements_66c,
      Companies_FieldIds.ytunnus_b80,
      Companies_FieldIds.company_info_762,
      Companies_FieldIds.fiscal_year_03b,
      Companies_FieldIds.deadline_for_financial_statement_16d,
      Companies_FieldIds.person_responsible_for_accounting_ba4,
      Companies_FieldIds.person_responsible_for_payroll_c04,
      Companies_FieldIds.person_responsible_for_client_6ba,
      Companies_FieldIds.shares_cd1,
      Companies_FieldIds.shares_listing_d5f,
      Companies_FieldIds.shares_metadata_f65,
      Companies_FieldIds.systems_9df,
      Companies_FieldIds.systems_in_use_a25,
      Companies_FieldIds.fiscal_year_updated_in_hailer_cdb,
      Companies_FieldIds.vat_calculation_created_618,
      Companies_FieldIds.vat_report_sent_61b,
      Companies_FieldIds.vat_paid_61f
    ],
    followers: [],
    isInitial: false,
    name: "🍗 Churn",
    possibleNextPhase: [
      Companies_PhaseIds.leads_a5b,
      Companies_PhaseIds.active_contact_a5c,
      Companies_PhaseIds.customers_a60
    ],
    possibleNextPhaseSettings: {}
  }
];