// Phases for workflow: KYC (SignSpace) - Form
      
import { KYC_SignSpace_Form_FieldIds, KYC_SignSpace_Form_PhaseIds } from "../enums";
      
export const phases: HailerPhaseUpdatePayload[] = [
  {
    _id: KYC_SignSpace_Form_PhaseIds.draft_6c2,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    fields: [
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.previous_kyc_6ed,
      KYC_SignSpace_Form_FieldIds.company_6ee,
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2
    ],
    followers: [],
    isEndpoint: false,
    isInitial: true,
    name: "Draft",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.sent_to_client_6c9
    ],
    possibleNextPhaseSettings: {}
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.send_document_to_signspace_6c3,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    fields: [
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Send document to SignSpace",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.needs_attention_6c4,
      KYC_SignSpace_Form_PhaseIds.sent_to_signspace_6c5,
      KYC_SignSpace_Form_PhaseIds.error_6c8
    ],
    possibleNextPhaseSettings: {},
    webhookUrl: "https://monolith.hailer.com/api/signspace/document",
    webhooksEnabled: true
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.needs_attention_6c4,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    fields: [
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Needs attention",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.draft_6c2,
      KYC_SignSpace_Form_PhaseIds.send_document_to_signspace_6c3,
      KYC_SignSpace_Form_PhaseIds.cancel_signing_request_6c7
    ],
    possibleNextPhaseSettings: {}
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.sent_to_signspace_6c5,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    fields: [
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Sent to SignSpace",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.signed_6c6,
      KYC_SignSpace_Form_PhaseIds.cancel_signing_request_6c7,
      KYC_SignSpace_Form_PhaseIds.send_document_to_signspace_6c3
    ],
    possibleNextPhaseSettings: {}
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.signed_6c6,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    fields: [
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Signed",
    possibleNextPhase: [],
    possibleNextPhaseSettings: {}
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.cancel_signing_request_6c7,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    fields: [
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Cancel signing request",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.draft_6c2,
      KYC_SignSpace_Form_PhaseIds.send_document_to_signspace_6c3,
      KYC_SignSpace_Form_PhaseIds.error_6c8
    ],
    possibleNextPhaseSettings: {},
    webhookUrl: "https://monolith.hailer.com/api/signspace/document",
    webhooksEnabled: true
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.error_6c8,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    fields: [
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Error",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.draft_6c2,
      KYC_SignSpace_Form_PhaseIds.send_document_to_signspace_6c3,
      KYC_SignSpace_Form_PhaseIds.cancel_signing_request_6c7
    ],
    possibleNextPhaseSettings: {}
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.sent_to_client_6c9,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    fields: [
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee,
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Sent to client",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.flagged_6ca,
      KYC_SignSpace_Form_PhaseIds.ready_for_signing_6cb,
      KYC_SignSpace_Form_PhaseIds.draft_6c2
    ],
    possibleNextPhaseSettings: {},
    webhookUrl: "https://rekna.critixlabs.fi/api/v1/email/send-kyc-invite",
    webhooksEnabled: true
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.flagged_6ca,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    enableAnnouncement: true,
    fields: [
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Flagged",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.ready_for_signing_6cb,
      KYC_SignSpace_Form_PhaseIds.cancel_signing_request_6c7,
      KYC_SignSpace_Form_PhaseIds.sent_to_client_6c9
    ],
    possibleNextPhaseSettings: {}
  },
  {
    _id: KYC_SignSpace_Form_PhaseIds.ready_for_signing_6cb,
    announcementFields: [],
    announcementFieldsOrder: [],
    announcementRecipients: [],
    description: "",
    enableAnnouncement: true,
    fields: [
      KYC_SignSpace_Form_FieldIds.financical_sanctions_6d4,
      KYC_SignSpace_Form_FieldIds.company_info_6d5,
      KYC_SignSpace_Form_FieldIds.company_name_6d6,
      KYC_SignSpace_Form_FieldIds.ytunnus_6d7,
      KYC_SignSpace_Form_FieldIds.address_6d8,
      KYC_SignSpace_Form_FieldIds.postal_code_6d9,
      KYC_SignSpace_Form_FieldIds.city_6da,
      KYC_SignSpace_Form_FieldIds.line_of_business_6db,
      KYC_SignSpace_Form_FieldIds.representative_6dc,
      KYC_SignSpace_Form_FieldIds.representative_name_6dd,
      KYC_SignSpace_Form_FieldIds.representative_title_6de,
      KYC_SignSpace_Form_FieldIds.representative_phone_number_6df,
      KYC_SignSpace_Form_FieldIds.representative_email_6e0,
      KYC_SignSpace_Form_FieldIds.representative_ytunnus_6e1,
      KYC_SignSpace_Form_FieldIds.business_activities_6e2,
      KYC_SignSpace_Form_FieldIds.financial_period_6e3,
      KYC_SignSpace_Form_FieldIds.share_capital_6e4,
      KYC_SignSpace_Form_FieldIds.estimated_revenue_6e5,
      KYC_SignSpace_Form_FieldIds.balance_sheet_total_amount_6e6,
      KYC_SignSpace_Form_FieldIds.number_of_personnel_6e7,
      KYC_SignSpace_Form_FieldIds.places_of_business_6e8,
      KYC_SignSpace_Form_FieldIds.is_the_company_subject_to_sanctions_6e9,
      KYC_SignSpace_Form_FieldIds.if_anyone_involved_in_the_company_under_sanctions_specify_6ea,
      KYC_SignSpace_Form_FieldIds.company_6ee
    ],
    followers: [],
    isEndpoint: false,
    isInitial: false,
    name: "Ready for signing",
    possibleNextPhase: [
      KYC_SignSpace_Form_PhaseIds.send_document_to_signspace_6c3,
      KYC_SignSpace_Form_PhaseIds.sent_to_client_6c9
    ],
    possibleNextPhaseSettings: {}
  }
];